window.papersData = (() => {
const topics = [
    { id: "all", label: "All topics" },
    { id: "randnla", label: "RandNLA and Iterative Solvers" },
    { id: "robust", label: "Robust Randomized Algorithms" },
    { id: "tensors", label: "Structured Sketching and Recovery" },
    { id: "factorizations", label: "Low-Rank and Kernel Methods" },
    { id: "sgd", label: "Optimization, Dynamics, and Regularization" },
    { id: "rmt", label: "Non-asymptotic Random Matrix Theory" }
];

const venueTypes = [
    { id: "all", label: "All venue types" },
    { id: "preprint", label: "Preprint/submitted" },
    { id: "journal", label: "Journal" },
    { id: "conference", label: "Conference/workshop" },
    { id: "survey", label: "Thesis and surveys" }
];

const papers = [
    {
        title: "Towards Universal Convergence of Backward Error in Linear System Solvers",
        authors: "M. Derezinski, Y. Nakatsukasa, E. Rebrova",
        year: 2026,
        venue: "Submitted",
        topic: "randnla",
        tags: ["randnla"],
        arxivId: "2604.16075",
        arxivYear: 2026,
        bibtexKey: "derezinski2026towards",
        bibtexAuthors: "Micha{\l} Derezi{\'n}ski and Yuji Nakatsukasa and Elizaveta Rebrova",
        resources: [{ label: "arXiv", url: "https://arxiv.org/abs/2604.16075" }]
    },
    {
        title: "Quantile Randomized Kaczmarz Algorithm with Whitelist Trust Mechanism",
        authors: "S. Shvaiko, L. Huang, E. Rebrova",
        year: 2026,
        venue: "Proc. ICASSP IEEE International Conference, pp. 721-725",
        topic: "robust",
        tags: ["robust", "randnla"],
        arxivId: "2602.12483",
        arxivYear: 2026,
        bibtexKey: "shvaiko2026quantile",
        bibtexAuthors: "Sofiia Shvaiko and Longxiu Huang and Elizaveta Rebrova",
        resources: [{ label: "arXiv", url: "https://arxiv.org/abs/2602.12483" }]
    },
    {
        title: "Attention Mechanisms Through the Lens of Numerical Methods: Approximation Methods and Alternative Formulations",
        authors: "M. F. Serret, A. Cortinovis, Y. Dong, D. Halikias, A. Ma, F. Matti, D. Needell, K. J. Pearce, E. Rebrova, D. Shur, R. Smith, H.-X. Wang, L. Grigori",
        year: 2026,
        venue: "arXiv preprint arXiv:2604.01757",
        venueType: "survey",
        topic: "factorizations",
        tags: ["factorizations"],
        arxivId: "2604.01757",
        arxivYear: 2026,
        bibtexKey: "serret2026attention",
        bibtexAuthors: "Michel Fabrice Serret and Alice Cortinovis and Yijun Dong and Diana Halikias and Anna Ma and Fabio Matti and Deanna Needell and Katherine J. Pearce and Elizaveta Rebrova and Disha Shur and Rudi Smith and Hai-Xiao Wang and Laura Grigori",
        resources: [{ label: "arXiv", url: "https://arxiv.org/abs/2604.01757" }]
    },
    {
        title: "Data-driven, ML-assisted approaches to problem well-posedness",
        authors: "T. Bertalan, G. A. Kevrekidis, E. D. Koronaki, S. Mishra, E. Rebrova, Y. G. Kevrekidis",
        year: 2026,
        venue: "PNAS Nexus 5 (6), pgag175",
        topic: "sgd",
        tags: ["sgd"],
        arxivId: "2503.19255",
        arxivYear: 2025,
        bibtexKey: "bertalan2026data",
        bibtexAuthors: "Tom Bertalan and George A. Kevrekidis and Eleni D Koronaki and Siddhartha Mishra and Elizaveta Rebrova and Yannis G. Kevrekidis",
        resources: [
            { label: "arXiv", url: "https://arxiv.org/abs/2503.19255" },
            { label: "Code", url: "https://github.com/tsbertalan/wellPosedness" }
        ],
        bibtex: `@article{bertalan2026data,
  title={Data-driven, ML-assisted approaches to problem well-posedness},
  author={Bertalan, T. and Kevrekidis, G. A. and Koronaki, E. D. and Mishra, S. and Rebrova, E. and Kevrekidis, Y.},
  journal={PNAS Nexus},
  volume={5},
  number={6},
  pages={pgag175},
  year={2026}
}`
    },
    {
        title: "Randomized Kaczmarz methods with beyond-Krylov convergence",
        authors: "M. Derezinski, D. Needell, E. Rebrova, J. Yang",
        year: 2025,
        venue: "SIAM Journal on Matrix Analysis and Applications 46 (4), 2558-2588",
        topic: "randnla",
        tags: ["randnla"],
        arxivId: "2501.11673",
        arxivYear: 2025,
        bibtexKey: "derezinski2025randomized",
        bibtexAuthors: "Micha{\l} Derezi{\'n}ski and Deanna Needell and Elizaveta Rebrova and Jiaming Yang",
        resources: [{ label: "arXiv", url: "https://arxiv.org/abs/2501.11673" }]
    },
    {
        title: "Scientific Applications Leveraging Randomized Linear Algebra",
        authors: "V. Patel, D. A. Maldonado, M. Melnichenko, N. Pritchard, V. Rao, E. Rebrova, S. Sankararaman, M. Schweitzer",
        year: 2025,
        venue: "arXiv preprint arXiv:2506.16457",
        venueType: "survey",
        topic: "randnla",
        tags: ["randnla", "factorizations"],
        arxivId: "2506.16457",
        arxivYear: 2025,
        bibtexKey: "patel2025scientific",
        bibtexAuthors: "Vivak Patel and D. Adrian Maldonado and Maksim Melnichenko and Nathaniel Pritchard and Vishwas Rao and Elizaveta Rebrova and Sriram Sankararaman and Marcel Schweitzer",
        resources: [{ label: "arXiv", url: "https://arxiv.org/abs/2506.16457" }],
        bibtex: `@article{patel2025scientific,
  title={Scientific Applications Leveraging Randomized Linear Algebra},
  author={Patel, Vivak and Maldonado, D. Adrian and Melnichenko, Maksim and Pritchard, Nathaniel and Rao, Vishwas and Rebrova, Elizaveta and Sankararaman, Sriram and Schweitzer, Marcel},
  journal={arXiv preprint arXiv:2506.16457},
  year={2025}
}`
    },
    {
        title: "Subspace-constrained randomized coordinate descent for linear systems with good low-rank matrix approximations",
        authors: "J. Lok, E. Rebrova",
        year: 2025,
        venue: "Accepted to SIAM Journal on Matrix Analysis and Applications",
        topic: "randnla",
        tags: ["randnla", "factorizations"],
        arxivId: "2506.09394",
        arxivYear: 2025,
        bibtexKey: "lok2025subspace",
        bibtexAuthors: "Jackie Lok and Elizaveta Rebrova",
        resources: [{ label: "arXiv", url: "https://arxiv.org/abs/2506.09394" }],
        bibtex: `@article{lok2025subspace,
  title={Subspace-constrained randomized coordinate descent for linear systems with good low-rank matrix approximations},
  author={Lok, Jackie and Rebrova, Elizaveta},
  journal={arXiv preprint arXiv:2506.09394},
  year={2025}
}`
    },
    {
        title: "Beyond Expectation: Concentration Inequalities for Randomized Iterative Methods",
        authors: "T. Anderson, M. Collins, J. Haddock, J. Lok, E. Rebrova",
        year: 2025,
        venue: "Submitted",
        topic: "randnla",
        tags: ["randnla"],
        arxivId: "2511.20877",
        arxivYear: 2025,
        bibtexKey: "anderson2025beyond",
        bibtexAuthors: "Toby Anderson and Max Collins and Jamie Haddock and Jackie Lok and Elizaveta Rebrova",
        resources: [{ label: "arXiv", url: "https://arxiv.org/abs/2511.20877" }]
    },
    {
        title: "On trimming tensor-structured measurements and efficient low-rank tensor recovery",
        authors: "S. Suryanarayanan, E. Rebrova",
        year: 2025,
        venue: "Submitted",
        topic: "tensors",
        tags: ["tensors"],
        arxivId: "2502.02843",
        arxivYear: 2025,
        bibtexKey: "suryanarayanan2025trimming",
        bibtexAuthors: "Shambhavi Suryanarayanan and Elizaveta Rebrova",
        resources: [{ label: "arXiv", url: "https://arxiv.org/pdf/2502.02843" }]
    },
    {
        title: "On regularization via early stopping for least squares regression",
        authors: "R. Sonthalia, J. Lok, E. Rebrova",
        year: 2025,
        venue: "Submitted",
        topic: "sgd",
        tags: ["sgd"],
        arxivId: "2406.04425",
        arxivYear: 2024,
        bibtexKey: "sonthalia2025regularization",
        bibtexAuthors: "Rishi Sonthalia and Jackie Lok and Elizaveta Rebrova",
        resources: [{ label: "PDF", url: "EarlyStopping2.pdf" }]
    },
    {
        title: "Discrete error dynamics of mini-batch gradient descent for least squares regression",
        authors: "J. Lok, R. Sonthalia, E. Rebrova",
        year: 2025,
        venue: "Proc. ALT Conference",
        topic: "sgd",
        tags: ["sgd"],
        arxivId: "2406.03696",
        arxivYear: 2024,
        bibtexKey: "lok2025discrete",
        bibtexAuthors: "Jackie Lok and Rishi Sonthalia and Elizaveta Rebrova",
        resources: [{ label: "arXiv", url: "https://arxiv.org/pdf/2406.03696.pdf" }]
    },
    {
        title: "Fine-grained analysis and faster algorithms for iteratively solving linear systems",
        authors: "M. Derezinski, D. LeJeune, D. Needell, E. Rebrova",
        year: 2025,
        venue: "Journal of Machine Learning Research 26 (144), 1-49",
        topic: "randnla",
        tags: ["randnla"],
        arxivId: "2405.05818",
        arxivYear: 2024,
        bibtexKey: "derezinski2025fine",
        bibtexAuthors: "Micha{\l} Derezi{\'n}ski and Daniel LeJeune and Deanna Needell and Elizaveta Rebrova",
        resources: [{ label: "arXiv", url: "https://arxiv.org/pdf/2405.05818.pdf" }]
    },
    {
        title: "Stochastic gradient descent for streaming linear and rectified linear systems with adversarial corruptions",
        authors: "H. Jeong, D. Needell, E. Rebrova",
        year: 2025,
        venue: "SIAM Journal on Mathematics of Data Science 7 (2), 516-541",
        topic: "robust",
        tags: ["robust", "sgd"],
        arxivId: "2403.01204",
        arxivYear: 2024,
        bibtexKey: "jeong2025stochastic",
        bibtexAuthors: "Halyun Jeong and Deanna Needell and Elizaveta Rebrova",
        resources: [{ label: "arXiv", url: "https://arxiv.org/pdf/2403.01204.pdf" }]
    },
    {
        title: "Learning nonnegative matrix factorizations from compressed data",
        authors: "A. Chaudhry, E. Rebrova",
        year: 2024,
        venue: "Accepted to SIAM Journal on Matrix Analysis and Applications",
        topic: "factorizations",
        tags: ["factorizations"],
        arxivId: "2409.04994",
        arxivYear: 2024,
        bibtexKey: "chaudhry2024learning",
        bibtexAuthors: "Abraar Chaudhry and Elizaveta Rebrova",
        resources: [{ label: "arXiv", url: "https://arxiv.org/abs/2409.04994" }]
    },
    {
        title: "A Subspace Constrained Randomized Kaczmarz method for structure or external knowledge exploitation",
        authors: "J. Lok, E. Rebrova",
        year: 2024,
        venue: "Linear Algebra and its Applications 698, 220-260",
        topic: "randnla",
        tags: ["randnla"],
        arxivId: "2309.04889",
        arxivYear: 2023,
        bibtexKey: "lok2024subspace",
        bibtexAuthors: "Jackie Lok and Elizaveta Rebrova",
        resources: [{ label: "arXiv", url: "https://arxiv.org/pdf/2309.04889.pdf" }]
    },
    {
        title: "Sharp analysis of sketch-and-project methods via a connection to randomized singular value decomposition",
        authors: "M. Derezinski, E. Rebrova",
        year: 2024,
        venue: "SIAM Journal on Mathematics of Data Science 6 (1), 127-153",
        topic: "randnla",
        tags: ["randnla"],
        arxivId: "2208.09585",
        arxivYear: 2022,
        bibtexKey: "derezinski2024sharp",
        bibtexAuthors: "Micha{\l} Derezi{\'n}ski and Elizaveta Rebrova",
        resources: [{ label: "arXiv", url: "https://arxiv.org/abs/2208.09585" }]
    },
    {
        title: "On subsampled Quantile Randomized Kaczmarz",
        authors: "J. Haddock, A. Ma, E. Rebrova",
        year: 2023,
        venue: "Proc. Allerton Conference",
        topic: "robust",
        tags: ["robust", "randnla"],
        arxivId: "2308.07987",
        arxivYear: 2023,
        bibtexKey: "haddock2023subsampled",
        bibtexAuthors: "Jamie Haddock and Anna Ma and Elizaveta Rebrova",
        resources: [{ label: "arXiv", url: "https://arxiv.org/abs/2308.07987" }]
    },
    {
        title: "Fast and low-Memory compressive sensing algorithms for low Tucker-rank tensor approximation from streamed measurements",
        authors: "C. Haselby, M. A. Iwen, D. Needell, E. Rebrova, W. Swartworth",
        year: 2025,
        venue: "Numerical Algorithms, 1-63",
        topic: "tensors",
        tags: ["tensors"],
        arxivId: "2308.13709",
        arxivYear: 2023,
        bibtexKey: "haselby2025fast",
        bibtexAuthors: "Cullen Haselby and Mark A. Iwen and Deanna Needell and Elizaveta Rebrova and William Swartworth",
        resources: [{ label: "arXiv", url: "https://arxiv.org/pdf/2308.13709.pdf" }]
    },
    {
        title: "Modewise operators, the tensor restricted isometry property, and low-rank tensor recovery",
        authors: "M. A. Iwen, D. Needell, M. Perlmutter, E. Rebrova",
        year: 2023,
        venue: "Applied and Computational Harmonic Analysis 66, 161-192",
        topic: "tensors",
        tags: ["tensors"],
        arxivId: "2109.10454",
        arxivYear: 2021,
        bibtexKey: "haselby2023modewise",
        bibtexAuthors: "Mark A. Iwen and Deanna Needell and Michael Perlmutter and Elizaveta Rebrova",
        resources: [{ label: "arXiv", url: "https://arxiv.org/abs/2109.10454" }]
    },
    {
        title: "Sparseness-constrained nonnegative tensor factorization for detecting topics at different time scales",
        authors: "L. Kassab, A. Kryshchenko, H. Lyu, D. Molitor, D. Needell, E. Rebrova, J. Yuan",
        year: 2023,
        venue: "Frontiers in Applied Mathematics and Statistics 10, 1287074",
        topic: "factorizations",
        tags: ["factorizations", "tensors"],
        arxivId: "2010.01600",
        arxivYear: 2020,
        bibtexKey: "kassab2024sparseness",
        bibtexAuthors: "Lara Kassab and Alona Kryshchenko and Hanbaek Lyu and Denali Molitor and Deanna Needell and Elizaveta Rebrova and Jiahong Yuan",
        resources: [{ label: "arXiv", url: "https://arxiv.org/abs/2010.01600" }]
    },
    {
        title: "On graph uncertainty principle and eigenvector delocalization",
        authors: "E. Rebrova, P. Salanevich",
        year: 2023,
        venue: "Proc. SAMPTA IEEE Conference",
        topic: "rmt",
        tags: ["rmt"],
        arxivId: "2306.15810",
        arxivYear: 2023,
        bibtexKey: "rebrova2023graph",
        bibtexAuthors: "Elizaveta Rebrova and Palina Salanevich",
        resources: [
            { label: "PDF", url: "https://openreview.net/pdf?id=p8wFnBshU4" },
            { label: "arXiv", url: "https://arxiv.org/pdf/2306.15810.pdf" }
        ]
    },
    {
        title: "On block accelerations of Quantile Randomized Kaczmarz for corrupted systems of linear equations",
        authors: "L. Cheng, B. Jarman, D. Needell, E. Rebrova",
        year: 2022,
        venue: "Inverse Problems 39 (2), 024002",
        topic: "robust",
        tags: ["robust", "randnla"],
        arxivId: "2206.12554",
        arxivYear: 2022,
        bibtexKey: "cheng2022block",
        bibtexAuthors: "Lu Cheng and Benjamin Jarman and Deanna Needell and Elizaveta Rebrova",
        resources: [{ label: "arXiv", url: "https://arxiv.org/abs/2206.12554" }]
    },
    {
        title: "Quantile-based iterative methods for corrupted systems of linear equations",
        authors: "J. Haddock, D. Needell, E. Rebrova, W. Swartworth",
        year: 2022,
        venue: "SIAM Journal on Matrix Analysis and Applications 43 (2), 605-637",
        topic: "robust",
        tags: ["robust", "randnla"],
        arxivId: "2009.08089",
        arxivYear: 2020,
        bibtexKey: "haddock2022quantile",
        bibtexAuthors: "Jamie Haddock and Deanna Needell and Elizaveta Rebrova and William Swartworth",
        resources: [{ label: "arXiv", url: "https://arxiv.org/abs/2009.08089" }]
    },
    {
        title: "Lower memory oblivious (tensor) subspace embeddings with fewer random bits: modewise methods for least squares",
        authors: "M. A. Iwen, D. Needell, E. Rebrova, A. Zare",
        year: 2021,
        venue: "SIAM Journal on Matrix Analysis and Applications 42 (1), 376-416",
        topic: "tensors",
        tags: ["tensors", "randnla"],
        arxivId: "1912.08294",
        arxivYear: 2019,
        bibtexKey: "iwen2022lower",
        bibtexAuthors: "M. A. Iwen and D. Needell and E. Rebrova and A. Zare",
        resources: [{ label: "arXiv", url: "https://arxiv.org/abs/1912.08294" }]
    },
    {
        title: "On a guided Nonnegative Matrix Factorization",
        authors: "J. Vendrow, J. Haddock, E. Rebrova, D. Needell",
        year: 2021,
        venue: "Proc. ICASSP IEEE Conference",
        topic: "factorizations",
        tags: ["factorizations"],
        arxivId: "2010.11365",
        arxivYear: 2020,
        bibtexKey: "vendrow2021guided",
        bibtexAuthors: "Joshua Vendrow and Jamie Haddock and Elizaveta Rebrova and Deanna Needell",
        resources: [{ label: "arXiv", url: "https://arxiv.org/abs/2010.11365" }]
    },
    {
        title: "Analysis of Legal Documents via Non-negative Matrix Factorization Methods",
        authors: "R. Budahazy, L. Cheng, Y. Huang, A. Johnson, P. Li, J. Vendrow, Z. Wu, D. Molitor, E. Rebrova, D. Needell",
        year: 2021,
        venue: "SCIURO undergraduate journal",
        topic: "factorizations",
        tags: ["factorizations"],
        arxivId: "2104.14028",
        arxivYear: 2021,
        bibtexKey: "budahazy2021analysis",
        bibtexAuthors: "Ryan Budahazy and Lu Cheng and Yihuan Huang and Andrew Johnson and Pengyu Li and Joshua Vendrow and Zhoutong Wu and Denali Molitor and Elizaveta Rebrova and Deanna Needell",
        resources: [{ label: "arXiv", url: "https://arxiv.org/abs/2104.14028" }]
    },
    {
        title: "On block Gaussian sketching for the Kaczmarz method",
        authors: "D. Needell, E. Rebrova",
        year: 2020,
        venue: "Numerical Algorithms 86 (1), 443-473",
        topic: "randnla",
        tags: ["randnla"],
        arxivId: "1905.08894",
        arxivYear: 2019,
        bibtexKey: "needell2021block",
        bibtexAuthors: "Deanna Needell and Elizaveta Rebrova",
        resources: [{ label: "arXiv", url: "https://arxiv.org/abs/1905.08894" }]
    },
    {
        title: "COVID-19 literature topic-based search via hierarchical NMF",
        authors: "R. Grotheer, K. Ha, L. Huang, Y. Huang, A. Kryshchenko, O. Kryshchenko, P. Li, X. Li, D. Needell, E. Rebrova",
        year: 2020,
        venue: "Proc. NLP-COVID19-EMNLP Workshop",
        topic: "factorizations",
        tags: ["factorizations"],
        resources: [{ label: "PDF", url: "https://openreview.net/pdf?id=toVkbxrY0V5" }],
        bibtex: `@inproceedings{grotheer2020covid,
  title={COVID-19 literature topic-based search via hierarchical NMF},
  author={Grotheer, R. and Ha, K. and Huang, L. and Huang, Y. and Kryshchenko, A. and Kryshchenko, O. and Li, P. and Li, X. and Needell, D. and Rebrova, E.},
  booktitle={Proc. NLP-COVID19-EMNLP Workshop},
  year={2020}
}`
    },
    {
        title: "Constructive regularization of the random matrix norm",
        authors: "E. Rebrova",
        year: 2020,
        venue: "Journal of Theoretical Probability 33 (3), 1768-1790",
        topic: "rmt",
        tags: ["rmt"],
        arxivId: "1809.03926",
        arxivYear: 2018,
        bibtexKey: "rebrova2020constructive",
        bibtexAuthors: "Elizaveta Rebrova",
        resources: [{ label: "arXiv", url: "https://arxiv.org/abs/1809.03926" }]
    },
    {
        title: "Scalable and memory-efficient kernel ridge regression",
        authors: "G. Chavez, E. Rebrova, Y. Liu, P. Ghysels, X. S. Li",
        year: 2020,
        venue: "Proc. 34th IPDSP IEEE Symposium",
        topic: "factorizations",
        tags: ["factorizations"],
        resources: [{ label: "PDF", url: "http://www-personal.umich.edu/~liuyangz/docs/KRR_ANN.pdf" }],
        bibtex: `@inproceedings{chavez2020scalable,
  title={Scalable and memory-efficient kernel ridge regression},
  author={Chavez, G. and Rebrova, E. and Liu, Y. and Ghysels, P. and Li, X. S.},
  booktitle={Proc. 34th IEEE International Parallel and Distributed Processing Symposium},
  year={2020}
}`
    },
    {
        title: "A parallel hierarchical blocked adaptive cross approximation algorithm",
        authors: "Y. Liu, W. Sid-Lakhdar, E. Rebrova, P. Ghysels, X. S. Li",
        year: 2020,
        venue: "International Journal of High Performance Computing Applications 34 (4), 394-408",
        topic: "factorizations",
        tags: ["factorizations"],
        resources: [{ label: "PDF", url: "http://www-personal.umich.edu/~liuyangz/docs/hierarchicalLR_IJHPCA.pdf" }],
        bibtex: `@article{liu2020parallel,
  title={A parallel hierarchical blocked adaptive cross approximation algorithm},
  author={Liu, Y. and Sid-Lakhdar, W. and Rebrova, E. and Ghysels, P. and Li, X. S.},
  journal={The International Journal of High Performance Computing Applications},
  volume={34},
  number={4},
  pages={394--408},
  year={2020}
}`
    },
    {
        title: "Sketching for Motzkin's iterative method for linear systems",
        authors: "E. Rebrova, D. Needell",
        year: 2019,
        venue: "Proc. 50th Asilomar Conference",
        topic: "randnla",
        tags: ["randnla"],
        arxivId: "1912.00771",
        arxivYear: 2019,
        bibtexKey: "needell2019sketching",
        bibtexAuthors: "Elizaveta Rebrova and Deanna Needell",
        resources: [{ label: "arXiv", url: "https://arxiv.org/pdf/1912.00771.pdf" }]
    },
    {
        title: "Norms of random matrices: local and global problems",
        authors: "E. Rebrova, R. Vershynin",
        year: 2018,
        venue: "Advances in Mathematics 324, 40-83",
        topic: "rmt",
        tags: ["rmt"],
        arxivId: "1608.06953",
        arxivYear: 2016,
        bibtexKey: "rebrova2018norms",
        bibtexAuthors: "Elizaveta Rebrova and Roman Vershynin",
        resources: [{ label: "arXiv", url: "https://arxiv.org/abs/1608.06953" }]
    },
    {
        title: "Coverings of random ellipsoids, and invertibility of matrices with i.i.d. heavy-tailed entries",
        authors: "E. Rebrova, K. Tikhomirov",
        year: 2018,
        venue: "Israel Journal of Mathematics 227 (2), 507-544",
        topic: "rmt",
        tags: ["rmt"],
        arxivId: "1508.06690",
        arxivYear: 2015,
        bibtexKey: "rebrova2018coverings",
        bibtexAuthors: "Elizaveta Rebrova and Konstantin Tikhomirov",
        resources: [{ label: "arXiv", url: "http://arxiv.org/pdf/1508.06690" }]
    },
    {
        title: "Spectral Properties of Heavy-Tailed Random Matrices (Ph.D. Thesis)",
        authors: "E. Rebrova",
        year: 2018,
        venue: "University of Michigan",
        topic: "rmt",
        tags: ["rmt"],
        resources: [
            { label: "PDF", url: "https://deepblue.lib.umich.edu/bitstream/handle/2027.42/146003/erebrova_1.pdf?sequence=1&isAllowed=y" }
        ],
        bibtex: `@phdthesis{rebrova2018spectral,
  title={Spectral Properties of Heavy-Tailed Random Matrices},
  author={Rebrova, E.},
  school={University of Michigan},
  year={2018}
}`
    },
    {
        title: "A study of clustering techniques and hierarchical matrix formats for kernel ridge regression",
        authors: "E. Rebrova, G. Chavez, Y. Liu, P. Ghysels, X. S. Li",
        year: 2018,
        venue: "IEEE International Parallel and Distributed Processing Symposium Workshop",
        topic: "factorizations",
        tags: ["factorizations"],
        arxivId: "1803.10274",
        arxivYear: 2018,
        bibtexKey: "chavez2018study",
        bibtexAuthors: "Elizaveta Rebrova and Gustavo Chavez and Yang Liu and Pieter Ghysels and Xiaoye Sherry Li",
        resources: [{ label: "arXiv", url: "https://arxiv.org/abs/1803.10274" }]
    }
];

return { topics, venueTypes, papers };
})();
